### ISSUE TITLE
Idea: Social/OpenGraph Images for listings

### ISSUE THREAD

**Issue by warrenbuckley** [umbraco/Umbraco.Marketplace.Issues#1]
When sharing a URL to a specific package it would be nice to have a nice preview/card of the package be it in Twitter, Slack etc
![image](https://user-images.githubusercontent.com/1389894/203552331-379bc45b-0800-46a6-875c-5999617aaa7a.png)

https://marketplace.umbraco.com/package/our.umbraco.taghelpers

**Comment by nathanwoulfe** [comment]
Soooo this is going to be a little more complex than I thought (not surprised though). We can't use dynamic meta tags because Twitter etc crawlers parse the server response, not the rendered page. Works fine for GA tracking since we can provide the exact data to track (eg pushing to data layer with the page details).

However, I think we could do something like this:
 - add rewrite/redirect configuration to handle known bot user agents
 - redirect requests to a different endpoint eg `/bot/package/my.package.id`
 - API returns a minimal response with the required og tags eg 
  ```
  <html>
    <head>
      <meta ... />
      <meta ... />
    </head>
    <body></body>
  </html>
```

**Comment by AndyButland** [comment]
This should be resolved with the next release using the method @nathanwoulfe suggested above.

**Comment by nathanwoulfe** [comment]
this is deployed, but doesn't appear to be working - will revisit.

**Comment by nathanwoulfe** [comment]
![image](https://user-images.githubusercontent.com/3248070/211229793-2b20f803-c634-4b21-ae60-729bcb0e29c7.png)
