### ISSUE TITLE
umbraco-marketplace.json not picked up from Github repository

### ISSUE THREAD

**Issue by D-Inventor** [umbraco/Umbraco.Marketplace.Issues#18]
I've included an umbraco-marketplace.json file in [my own github repository](https://github.com/Infocaster/UrlTracker).
I've also published a [package on NuGet](https://www.nuget.org/packages/UrlTracker) with the `umbraco-marketplace` tag.
The information does not seem to show up on the Umbraco marketplace.

**Comment by AndyButland** [comment]
Hi @D-Inventor - thanks for taking the trouble to list your package and letting use know about the problem.   I think the issue is with the list of contributors in your file.  You have them as an array of names, but the expectation here is an array of objects, each containing a name and an optional URL.

There's an example showing contributors [here](https://github.com/AndyButland/Anaximapper/blob/main/umbraco-marketplace.json) for reference.

I checked validating against the schema and that was the only issue I could see, so I believe if you correct that it should get imported OK.

**Comment by D-Inventor** [comment]
Thank you for your reply! I've corrected my error now. I'll check later to see if my marketplace file has been picked up

**Comment by AndyButland** [comment]
Thanks, it looks to have come through OK now.
