### ISSUE TITLE
"Recently added" packages

### ISSUE THREAD

**Issue by dalyUSN** [umbraco/Umbraco.Marketplace.Issues#31]
At the moment the "Recently Added" packages on the homepage are based on the most recent initial release of a package. 

Would it make more sense for this to be based on the most recently released version of a package? 

For instance, if a package releases a new version to support the latest Umbraco release then it would be more useful for users to see that package instead of a package's initial release which could be for a previous Umbraco.

If others do not agree with this then perhaps there could be a new row of "Recently Updated" packages.

It would be good to know others' thoughts on this.

I'm hoping with this suggestion we can make the Marketplace more relevant.

**Comment by nathanwoulfe** [comment]
Hi @dalyUSN, just realised we'd never replied - so firstly, apologies for that.

I've been looking at sorting today, and found it's a bit tricky, because we have different dates from different sources, which may not always make sense chronologically.

The sorting for recently added is based on the package creation date in the Marketplace repository, so is fully independent of versioning etc at the NuGet end. Recently modified sorts on the modification date in our repository (which may not always be triggered by a useful change for our users), but we also have a published date field, which is the date the package was most recently published to NuGet. Published date is not currently in use.

This then means it's possible for a package to be published before it was created (eg I publish v1.0.0 to NuGet, package is imported to the Marketplace in the next import run, so is created after being published). Would be confusing if we displayed the dates, but at the moment, we don't.

So in answering your query, I think it makes sense to sort updated using the NuGet published date (as this is most useful change to consider an update), and sort recently created using the repository record creation date. That does mean the two result sets could appear to conflict, but again, since we're not displaying the dates, I don't think it's a big issue. There's potential for a package to be published to NuGet with invalid Marketplace metadata, so isn't imported until the metadata is fixed, therefore creating a larger timespan between published and created dates, but also something I don't see as a problem.

And I just realised I kinda missed answering your question re recently updated vs recently added on the hompage. Easy enough to implement, and I don't see any obvious reason why we wouldn't add a third set of cards. 

I'll run all of the above back through the team, and let you know what is decided.

**Comment by ronaldbarendse** [comment]
We currently have the following orderings:
- **Most active installs**: the number of installations reporting using the package within the last 14 days.
- **Most downloads**: the all-time number of downloads as reported by NuGet.
- **Recently added**: the date the package was first added to the Umbraco Marketplace.
- **Recently updated**: the date the package was last updated as reported by NuGet.

And on the package view, both the **Updated** and **Listed on Marketplace** dates are now shown, so this should make it clear on what dates are used for the actual ordering.

@nathanwoulfe The 'Recently updated' description is currently not yet included in the pop-up in the filter and the [direct route](https://marketplace.umbraco.com/all/updated) doesn't seem to work anymore (as mentioned in https://github.com/umbraco/Umbraco.Marketplace.Issues/issues/45#issuecomment-1502456855).

**Comment by nathanwoulfe** [comment]
Will have a look at that route today - likely died when we flipped the default ordering, which let us with missing order-by enum values for some routes.

**Comment by nathanwoulfe** [comment]
Fixes will be live shortly - CD running now 😄

**Comment by dalyUSN** [comment]
Hey Nathan, thanks for all the updates on this. 

Will a "Recently Updated" row be added to the Marketplace homepage? I think this would be really beneficial.

**Comment by AndyButland** [comment]
It's already there @dalyUSN - we show "Recently added" and "Most popular" in two rows on the home page.  There's some alternation between which appears above the other.

**Comment by dalyUSN** [comment]
Hey Andy. Ye, I can see "Recently **Added**", I'm asking about "Recently **Updated**". As in, can there be a row of the packages that have been updated recently?

**Comment by dalyUSN** [comment]
Once viewing the full listings/categories, you can filter by "Recently Updated", so the data is there to support it. I just reckon this would be very beneficial to users when they land on the homepage. It would also encourage package creators to continue to maintain their packages by showcasing new updates.

**Comment by AndyButland** [comment]
Ah, sorry... I read and replied too quickly.  Yes, I guess we could consider that.

Am thinking though @nathanwoulfe maybe though we should tighten up what "Recently updated" means?  Currently it's picking up any change to the data we pull into the Marketplace, but probably it should be limited to when a new version is released.  That would mean there's actually an update to the package itself, not just in some of the meta data we load.

**Comment by dalyUSN** [comment]
No worries @AndyButland — easily done. 

Tightening up the meaning around "Recently Updated" sounds great too!

**Comment by nathanwoulfe** [comment]
@AndyButland that sounds sensible - will reduce opportunities for gaming the system too, since the threshold for being treated as updated would be higher, so not as easy to jump back to the top of the list.

I see no reason why we wouldn't add an additional set to the homepage. Having two sets below the CTA panel would help add weight to the homepage too, it's 50% more cards!

**Comment by AndyButland** [comment]
This has been added now to the Marketplace home page.

**Comment by dalyUSN** [comment]
Nice one, looks great!
