### ISSUE TITLE
Additional file - umbraco-marketplace.json is not working as expected

### ISSUE THREAD

**Issue by wtct** [umbraco/Umbraco.Marketplace.Issues#34]
Hi,

Yesterday, we published our **UmbraCare.DedicatedMediaFolder** package for all recent Umbraco versions. 

https://www.nuget.org/packages/UmbraCare.DedicatedMediaFolder/

Unfortunately the [umbraco-marketplace.json](https://umbracare.net/umbraco-marketplace.json) is not working as expected because we don't see screenshots, video and tags:

https://marketplace.umbraco.com/package/umbracare.dedicatedmediafolder

Could you please help us solve this issue?

Thanks in advance!

**Comment by AndyButland** [comment]
Hi @wtct - I think the issue here is that you don't have the file hosted where we are expecting it, which is in the directory under the project URL you have configured in the NuGet package.

It's currently being looked for here:
https://umbracare.net/products/dedicated-media-folder/umbraco-marketplace.json

But I can see you have it here:
https://umbracare.net/umbraco-marketplace.json

So if you can move it to the expected location it should get picked up.

**Comment by wtct** [comment]
> Hi @wtct - I think the issue here is that you don't have the file hosted where we are expecting it, which is in the directory under the project URL you have configured in the NuGet package.
> 
> It's currently being looked for here: https://umbracare.net/products/dedicated-media-folder/umbraco-marketplace.json
> 
> But I can see you have it here: https://umbracare.net/umbraco-marketplace.json
> 
> So if you can move it to the expected location it should get picked up.

Hi @AndyButland , Thanks for your answer. It's working now. However, site has only one root in my opinion :) 

> This file must exist in the root of the URL defined as the project URL in your NuGet specification.

https://marketplace.umbraco.com/listing

**Comment by AndyButland** [comment]
Good to hear, and fair point... I'll see if we can clarify that in the instructions.
