### ISSUE TITLE
Urgent: Package URL is not working in Umbraco Marketplace

### ISSUE THREAD

**Issue by wtct** [umbraco/Umbraco.Marketplace.Issues#35]
Hi!

We have just noticed that URL to the our published package is not working (404):

https://marketplace.umbraco.com/package/umbracare.dedicatedmediafolder

Our campaign with broken link is running :( 

Could you please take a look? Probably it's caused by dot in the package name (URL as well).

BTW, URL for uSync.Complete is not working as well:

https://marketplace.umbraco.com/package/usync.complete

**Comment by AndyButland** [comment]
I've deployed a fix for this, but unfortunately have had to change the URL structure slightly.  It seems allowing a `.` in the URL in this place interferes with dotnet's routing, I guess as it considers it to be a path to a file rather than a route to send to a controller.  I tried a few options with static file settings and route configuration, but couldn't get it to work.

So what I've done is introduce a replacement of `.`. with `_` when rendering URLs (and back the other way when looking up a package by it's NuGet Id).

So your package is now accessible on a direct link of:
https://marketplace.umbraco.com/package/umbracare_dedicatedmediafolder

Similarly:
https://marketplace.umbraco.com/package/usync_complete
https://marketplace.umbraco.com/package/umbraco_forms

Maybe we'll find a better way to do this and allow the `.` characters back, but for now at least this is better as each package now has a deep link that works correctly.

**Comment by nathanwoulfe** [comment]
I have a feeling this was related to how we previously handled 404s (which were thrown by any request to a non-dotnet-routed route). Essentially, 404s were swallowed and returned to browser to manage in the SPA, however that had other impacts (can't recall exactly) so had to be reverted. As Andy said, it should be possible to make `.` work, but underscore will need to be it for now.

**Comment by AndyButland** [comment]
I'll be deploying a further update to resolve this issue later today, which will mean we can go back to the URLs with the "." in them.

Sorry for messing you about @wtct if you've had to change the URL you are linking from.

However what I did yesterday as a fix isn't ideal as it relies on character replacements, which are easily missed, and if and when we have a package with an "_" in the name, we'll have a problem again.

As it turned out there was a fairly easy way to get the routing working with the "." in the request... I just needed to wait for daytime in Australia to have it pointed out to me!  Am testing the second fix now but please expect an update to live in the next hour or so.
