### ISSUE TITLE
Odd + button appearing on some items

### ISSUE THREAD

**Issue by greystate** [umbraco/Umbraco.Marketplace.Issues#37]
I've just noticed there's a plus button placed on the third item in the **Most popular** row, and on the 4th item in the **Recently added** row...

I'm seeing this in "all browsers" ...

![theplusbutton](https://user-images.githubusercontent.com/5463/213399716-780a423b-936e-4e40-8009-7e331eee2218.jpg)

**Comment by AndyButland** [comment]
Thanks.  It's there to expand the description, which it is doing... but looks like it's also triggering the load of the package details that happens when you click anywhere on the package card.  It should only do the former.

**Comment by greystate** [comment]
Ah that's so weird, as I was _really_ trying to figure out what the logic was to put in on "some" cards... 🙈 

(I'm just secretly happy that the expand function doesn't actually work, so I don't feel I'm completely wasting everyone's time by logging a non-bug 😬)

**Comment by nathanwoulfe** [comment]
Fix for this will be on dev shortly - issue was introduced when we swapped the card element from `button` to `a`, so that we could improve the routing experience (ie updating URL when a card is opened). Switched back to `button` and added manual push to the history stack, all looks to be working correctly again.
