### ISSUE TITLE
Unable to override Title using the umbraco-marketplace.json

### ISSUE THREAD

**Issue by prmeyn** [umbraco/Umbraco.Marketplace.Issues#41]
In the [blog Umbraco Marketplace Update - January 2023](https://umbraco.com/blog/umbraco-marketplace-update-january-2023/)  the following is mentioned

> As a straightforward example, mentioning the word Umbraco in the title or description on NuGet makes a lot of sense, but on the marketplace, everything is related to Umbraco.  By populating the Title and/or Description field of the `umbraco-marketplace.json` file, we'll display that instead of the value retrieved from NuGet.

I have tried to follow the above in my package's [`umbraco-marketplace.json`](https://github.com/prmeyn/UmbracoOutputCache/blob/89ac708445230f3da59814c5df972f9e63233948/umbraco-marketplace.json#L3) but the package name in the [new Umbraco marketplace still seems to have Umbraco prefixed](https://marketplace.umbraco.com/package/umbracooutputcache).

**Comment by nathanwoulfe** [comment]
Heya @prmeyn I think this is an us-problem, not a you-problem - we're investigating an issue with our package sync task, which seems to have fallen over. Once we resolve this, expect your listing to update.

Noticed too the category for your package is lower case, it should read `Developer Tools`. If you update that in the JSON too, your package will appear on the category page (once the sync task is fixed).

I'll close this one as there's no work to be done.

**Comment by AndyButland** [comment]
Hi @prmeyn - I think the issue here is also that you are missing a [ProjectUrl](https://learn.microsoft.com/en-us/nuget/reference/nuspec#projecturl) in your NuGet package.  Without that we don't have something to follow to find your `umbraco-marketplace.json` file.

If you compare [yours](https://nuget.info/packages/Anaximapper/1.0.3) with [this one](https://nuget.info/packages/Anaximapper/1.0.3), you'll see yours is missing the "Package Information" link, which comes from this setting.

You can add it in your `.csproj` file, like you see [here](https://github.com/AndyButland/Anaximapper/blob/main/Anaximapper/Anaximapper.csproj#L11).

**Comment by prmeyn** [comment]
![image](https://user-images.githubusercontent.com/100074068/215403478-a8ce9763-73ea-496b-aa6b-8aa5b162a14d.png)
Thank you both, I guess the validation tool has still not recovered from its fall, I'll wait and check back in 24 hours, to see if the above suggestions have helped fix this issue.

**Comment by nathanwoulfe** [comment]
Hey @prmeyn looks like we're back in business - validation tools are working again (pretty sure it was a transient NuGet API issue), validation for UmbracoOutputCache ran successfully. I've requested a package sync, which should take a few minutes to complete.

**Comment by prmeyn** [comment]
> Hey @prmeyn looks like we're back in business - validation tools are working again (pretty sure it was a transient NuGet API issue), validation for UmbracoOutputCache ran successfully. I've requested a package sync, which should take a few minutes to complete.

Thanks, everything looks good in the marketplace too. :)
