### ISSUE TITLE
Package details view can't be closed using `esc` key

### ISSUE THREAD

**Issue by bjarnef** [umbraco/Umbraco.Marketplace.Issues#50]
When the details view is open it can be closed via the close-button in upper right corner, but not using `esc` key, which it should to make the site accessible.

![image](https://github.com/umbraco/Umbraco.Marketplace.Issues/assets/2919859/69be4db0-ccbc-4809-9c65-41f1143c44cf)

**Comment by nathanwoulfe** [comment]
Hey @bjarnef, thanks for the heads-up - this was working previously, I must have borked it when I refactored the routing for the overlay. Will get it sorted.

**Comment by nathanwoulfe** [comment]
Will be fixed in our next deployment - there were some changes to component nesting which meant elements previously at the document root (and available to `document.querySelectorAll`) had moved into a different component and hence a different shadow DOM so were no longer queryable. Changed to use a DOM-piercing query and all is good again.
