### ISSUE TITLE
Umbraco 12 support

### ISSUE THREAD

**Issue by abjerner** [umbraco/Umbraco.Marketplace.Issues#52]
I noticed on the Marketplace that most packages now support Umbraco 12, which surprised me a bit, since it has only been out since this morning.

It seems be because a lot of packages doesn't have an upper bound for which Umbraco version is supported. Not to pick on Sebastiaan, but for instance his Hangfire package support all versions of Umbraco from 10.0.0 and up:

![image](https://github.com/umbraco/Umbraco.Marketplace.Issues/assets/3634580/7551d8c5-04af-4b5e-a8ee-7a30748b83d2)

It most likely also works with Umbraco 12, but looking beyond Sebastiaan's package, I could suspect that not all packages do.

So my question is now - is it a problem that some packages (maybe unintentionally) claim to support Umbraco versions they may or may not support? I don't know what the correct approach is, but I think it's at least fair to ask the question.

Before the Marketplace I didn't specify an upper version bound either, but I started doing this to make the supported versions more correct. Downside is that even though I didn't have to make any changes to my Skybrud Redirects package to support Umbraco 12, I did have to push a new release today with an upper version bound that allows using it with Umbraco 12. And now I have to do the same for all my other packages. So I guess there are pros and cons either way.

**Comment by AndyButland** [comment]
Yes, I agree. it could be - but I don't think there's too much we can or should do about this on the Marketplace.  We leave it up to package developers to use NuGet to indicate which versions they support.  And present what is claimed.

As you say, by providing only a minimum version, the developer is claiming support for anything above that - for 10, 11, 12 that maybe likely for many; when we get to 14 probably not.  With the [HQ products](https://www.nuget.org/packages/Umbraco.Forms.Core/) we now specify a maximum, but then as you say have to release a new one for new Umbraco majors.  But at least we can be sure when we've done that that we've tested it and are explicitly confirming support.  So I think that is the better approach, but I can equally see why an open-source package developer with limited time might prefer to take a slightly less strict approach, and then deal with issues if reported.

**Comment by ronaldbarendse** [comment]
As Andy mentioned, adding maximum dependency versions is something for the developer to decide, because it depends on the type of package (how much public APIs are used, backend/frontend code, etc.) and whether you want to be explicit on what (future) versions are supported.

A bump in the major version implicitly means that it can contain breaking changes, but you won't know in advance whether your package will work in a future major version (although you can get a general idea if you keep track of the [breaking changes announcements](https://github.com/umbraco/Announcements/issues)).

You can take the defensive approach and limit your package to only allow majors that are verified to work (requiring you to release a new version to update the maximum dependency version). Or you take the reactive approach by omitting the maximum dependency version and only if there's an issue on a new major version, either fix that or add the version limit afterwards (both also requiring a new release).

There's not really anything we can currently do in the Marketplace to fix this, although this is definitely something we could add to the package good practice documentation (see [Docs PR](https://github.com/umbraco/UmbracoDocs/pull/5156)) and maybe even have a flag/option in the package template to add this maximum version for you...
